# Generated by Django 4.0.3 on 2022-07-23 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=120)),
                ('job_description', models.TextField()),
                ('role', models.CharField(max_length=120)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('salary', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=120)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_date', models.DateField(null=True)),
                ('qualification', models.CharField(max_length=120, null=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120, unique=True)),
                ('logo', models.ImageField(upload_to='images')),
                ('bio', models.CharField(max_length=120)),
                ('services', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'applied'), ('rejected', 'rejected'), ('pending', 'pending'), ('cancelled', 'cancelled'), ('accepted', 'accepted')], default='applied', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajob', to='employers.jobs')),
            ],
        ),
    ]
